import express from "express";
import authMiddleware from "../middleware/authMiddleware.js";
import checkPermission from "../middleware/permissionsMiddleware.js";
import {overview,saveProgram,createMember,addTransaction,createReward,createCampaign} from "../controllers/loyaltyController.js";
const router=express.Router();
router.get("/",authMiddleware,checkPermission("view_loyalty"),overview);
router.post("/programs",authMiddleware,checkPermission("manage_loyalty_program"),saveProgram);
router.post("/members",authMiddleware,checkPermission("manage_loyalty_members"),createMember);
router.post("/transactions",authMiddleware,checkPermission("manage_loyalty_members"),addTransaction);
router.post("/rewards",authMiddleware,checkPermission("manage_loyalty_campaigns"),createReward);
router.post("/campaigns",authMiddleware,checkPermission("manage_loyalty_campaigns"),createCampaign);
export default router;
